adjective = input("adjective: ")
adjective1 = input("adjective: ")
bird = input("type of bird: ")
house = input ("room in a house: ")
past_verb = input("verb past tense: ")
verb = input ("verb: ")
relavtive = input ("relative's name: ")
noun = input("noun: ")
liquid = input ("a liquid: ")
verb_ending_ing = input ("verb ending in -ing: ")
part_of_the_body = input("part of the body (plural): ")
plural_noun = input("plural noun: ")
verb_ending_ing2 = input("verb ending in -ing: ")
noun2 = input("noun: ")

print("\n")
print("It was a ",adjective, "cold November day. I woke up to the ",adjective1)
print("smell of ",bird, "roasting in the ",house, "downstairs. I ",past_verb)
print("down the stairs to see if I could help ",verb, "the dinner. My mom")
print("said, See if",relavtive, "needs a fresh poodle.\n")
print("So I carried a tray of glasses full of ", liquid, "into the ", verb_ending_ing)
print("room. When I got there, I couldn't believe my ", part_of_the_body, "! There")
print("were ",plural_noun, verb_ending_ing2,"on the", noun2,"!")