import turtle
ANGLE = 50
def turtle_rectangle(x, y, width, height, pencolor, fillcolor):
    turtle.up()
    turtle.goto(x, y)
    turtle.pencolor(pencolor)
    turtle.fillcolor(fillcolor)
    turtle.begin_fill()
    turtle.down()
    turtle.forward(width)
    turtle.left(90)
    turtle.forward(height)
    turtle.left(90)
    turtle.forward(width)
    turtle.left(90)
    turtle.forward(height)
    turtle.left(90)
    turtle.up()
    turtle.end_fill()

def turtle_triangle(x, y, base, penColor, fillColor):
    turtle.up()
    turtle.goto(x, y)
    turtle.pencolor(penColor)
    turtle.fillcolor(fillColor)
    turtle.begin_fill()
    turtle.down()
    turtle.forward(base)
    turtle.left(120)
    turtle.forward(base)
    turtle.left(120)
    turtle.forward(base)
    turtle.left(120)
    turtle.up()
    turtle.end_fill()

def turtle_circle(x, y, penColor, fillColor, radius):
    turtle.up()
    turtle.goto(x, y)
    turtle.down()
    turtle.pencolor(penColor)
    turtle.fillcolor(fillColor)
    turtle.begin_fill()
    turtle.circle(radius)
    turtle.end_fill()

def main():
    turtle.speed(0)
    turtle_rectangle(-500, -200, 950, 550, "black", "Skyblue")
    turtle_rectangle(-500, -200, 950, 150, "black", "sandybrown")
    turtle_circle(-300, 150, "black", "yellow", 55)
    turtle_triangle(-200, -50, 100, "black", "wheat")
    turtle_triangle(-100, -50, 300, "black", "wheat")
    turtle_triangle(200, -50, 200, "black", "wheat")
    turtle_circle(200, 200, "white", "white", 20)
    turtle_circle(180, 180, "white", "white", 20)
    turtle_circle(170, 190, "white", "white", 20)
    turtle_circle(210, 190, "white", "white", 20)
    turtle_circle(205, 185, "white", "white", 20)
    turtle_circle(-250, 150, "white", "white", 20)
    turtle_circle(-230, 150, "white", "white", 20)
    turtle_circle(-240, 140, "white", "white", 20)
    input()

main()